version: '3.8'

services:
  calculadora-app:
    build:
      context: .
    container_name: calculadora-saas
    restart: unless-stopped
    # Aponta para a pasta /srv/ para evitar problemas de permissão
    volumes:
      - /srv/calculadora-data/leads.db:/app/leads.db
      - /srv/calculadora-data/completed_pdfs:/app/completed_pdfs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculadora-secure.rule=Host(`calculotrabalhista.mbbaj.adv.br`)"
      # Prioridade alta para vencer o WordPress
      - "traefik.http.routers.calculadora-secure.priority=200"
      - "traefik.http.routers.calculadora-secure.entrypoints=websecure"
      - "traefik.http.routers.calculadora-secure.tls=true"
      # Nome correto do gerador de certificados
      - "traefik.http.routers.calculadora-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.calculadora-secure.service=calculadora-service"
      - "traefik.http.services.calculadora-service.loadbalancer.server.port=3000"
    networks:
      - calculadora

networks:
  calculadora:
    external: true