version: '3.8'

services:
  calculadora-app:
    build:
      context: .
    container_name: calculadora-saas
    restart: unless-stopped
    volumes:
      - calculadora-db:/app/leads.db
      - calculadora-pdfs:/app/completed_pdfs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculadora-http.rule=Host(`calculotrabalhista.mbbaj.adv.br`)"
      - "traefik.http.routers.calculadora-http.entrypoints=web"
      - "traefik.http.routers.calculadora-http.middlewares=https-redirect"
      - "traefik.http.routers.calculadora-secure.rule=Host(`calculotrabalhista.mbbaj.adv.br`)"
      - "traefik.http.routers.calculadora-secure.priority=200"
      - "traefik.http.routers.calculadora-secure.entrypoints=websecure"
      - "traefik.http.routers.calculadora-secure.tls=true"
      - "traefik.http.routers.calculadora-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.calculadora-secure.service=calculadora-service"
      - "traefik.http.services.calculadora-service.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
    networks:
      - calculadora

volumes:
  calculadora-db:
  calculadora-pdfs:

networks:
  calculadora:
    external: true