version: '3.8'

services:
  calculadora-app:
    build:
      context: .
    container_name: calculadora-saas
    restart: unless-stopped

    # A MUDANÇA CRÍTICA ESTÁ AQUI:
    # Em vez de apontar para uma pasta específica na VPS,
    # dizemos ao Docker para usar o "cofre" chamado 'calculadora-storage'
    # e conectá-lo à pasta /app inteira dentro do contêiner.
    volumes:
      - calculadora-storage:/app

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculadora-secure.rule=Host(`calculotrabalhista.mbbaj.adv.br`)"
      - "traefik.http.routers.calculadora-secure.entrypoints=websecure"
      - "traefik.http.routers.calculadora-secure.tls=true"
      - "traefik.http.routers.calculadora-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.calculadora-secure.service=calculadora-service"
      - "traefik.http.services.calculadora-service.loadbalancer.server.port=3000"
    networks:
      - calculadora

# Aqui declaramos o nosso "cofre" gerido pelo Docker
volumes:
  calculadora-storage:

networks:
  calculadora:
    external: true